### PR TITLE
enable build on OpenJDK-15 by bumping to

### PR DESCRIPTION
**Pull request by axtimwalde**
maven-enforcer-plugin-3.0.0-M3
jacoco-maven-plugin-0.8.6

### CODE REVIEW

**Comment by ctrueden** [comment]
@axtimwalde This is great. Have you tested this new enforcer with existing projects, with enforcer enabled, and older JDKs (8 and 11)? If all still works, should be no problem to merge immediately. I'm just a bit cautious about the bump from enforcer 1.4 to 3.0.0-M3—that's a big leap, and I'd like to have some confidence that our existing build workflows will still function. (I did double check the commit history, and there was never a rollback of enforcer plugin version from a later version, which suggests to me that there are no known problem with versions newer than 1.4.1.)

**Comment by axtimwalde** [comment]
I tested in n5 with enforcers enabled and on both OpenJDK 8 and OpenJDK 15.  I will soon test on n5-hdf5.  I understand that this is minimal and therefore started this as an info thread on gitter but was advised to PR directly.

**Comment by hinerm** [comment]
@axtimwalde I'll test this with the melting pot. Thanks for your all your explorations with newer JDKs!

**Comment by ctrueden** [comment]
@hinerm Thanks. One way to test this change would be to run the melting pot with `-s` to skip the build, then go in and add `-Dmaven-enforcer-plugin.version=3.0.0-M3` and `-Djacoco-maven-plugin=0.8.6` to the `build.sh` script.

**Comment by axtimwalde** [comment]
Polite bump.  Thanks!

**Comment by hinerm** [comment]
@ctrueden why is the enforcer [skipped in the melting pot](https://github.com/scijava/pom-scijava/blob/65e4ed61c20c5226ce214c49a053e3aba5a6c0e2/melting-pot.sh#L651)?

**Comment by hinerm** [comment]
@axtimwalde sorry Saalfeld. It took me a while to get comfortable with the melting pot, and it looks like ImageJ `1.53d` blew up some API, so we are getting failures all over.

I'm currently melting vs. `1.53c` and if that works I'm happy to merge this PR.

**Pull request merged**
