### PR TITLE
enable JDK versions >8 as a build platform

### PR DESCRIPTION
**Pull request by axtimwalde**
not to confuse with target which is still 1.8

### CODE REVIEW

**Comment by ctrueden** [comment]
I don't think this is a good idea. If you want to use a different version to build your project, override `scijava.jvm.build.version` in your own POM to whatever you need. Building a Java-8-compatible project with a version of Java newer than 8 invites generation of bytecode that won't actually work in a Java 8 runtime.

**Comment by ctrueden** [comment]
Here's an example of it going south:
```
$ cat X.java
public class X {
  public static void main(String... args) {
    System.out.println(java.io.OutputStream.nullOutputStream());
  }
}

$ /Library/Java/JavaVirtualMachines/adoptopenjdk-11.jdk/Contents/Home/bin/javac -source 1.8 -target 1.8 X.java
warning: [options] bootstrap class path not set in conjunction with -source 8
1 warning

$ /Library/Java/JavaVirtualMachines/adoptopenjdk-11.jdk/Contents/Home/bin/java X
java.io.OutputStream$1@5fdef03a

$ /Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home/bin/java X
Exception in thread "main" java.lang.NoSuchMethodError: java.io.OutputStream.nullOutputStream()Ljava/io/OutputStream;
	at X.main(X.java:3)
```

**Comment by axtimwalde** [comment]
This must be a bug!  If this specification is correct https://docs.oracle.com/en/java/javase/15/docs/specs/man/javac.html#option-target then the sole purpose of the `-target` flag is to enable cross-compilation that is guaranteed to run on the target platform.  We should therefore exclude build platforms that do NOT enable building for 1.8, not those that do.  Pragmatically, I would override this in all our projects now as soon as I have to build them which will render this constraint in pom-scijava-base useless.

**Comment by ctrueden** [comment]
Call it a bug if you want, but it's longstanding behavior. Here's the bug report about it:

https://bugs.openjdk.java.net/browse/JDK-8058150

And it's fixed in Java 9 in that there's a new flag, `--release`, to also set the bootclasspath to prevent this issue of "accidentally" using too-new API.

Once we've upgraded our whole component stack to Java 11, we could start using `--release` and then we wouldn't need to restrict the build platform in this way anymore. But as long as we're still on Java 8, it needs to stay in place.

**Comment by ctrueden** [comment]
> I would override this in all our projects now as soon as I have to build them which will render this constraint in pom-scijava-base useless.

I'd encourage you to instead override it locally in your `~/.m2/settings.xml`. (I think this should work, though I haven't tested it personally.) Otherwise, you weaken the protections of CI builds, for example.

OK, I gotta get back to not working! 😁 💨

**Comment by axtimwalde** [comment]
I understand.  I also have investigated a bit.  The correct way to do this on anything >8 is with the `--release` flag which accepts the non-`1.` numbers 8, 9, ..., 14.  The maven compiler plugin supports this via the `<maven.compiler.release>` property.  I tried this and it works great if the building platform is JDK 9 or later.  Unfortunately, the maven compiler plugin is not smart enough to not translate this property if the building platform is JDK 8 which does not know it yet and then breaks with a naive `Fatal error compiling: invalid flag: --release -> [Help 1]`. So we could have it all if we could convince the maven compiler plugin to use this option only if the building JDK is not 8.  I was not yet successful finding out how to do this but will keep investigating.

**Comment by axtimwalde** [comment]
I am currently reading https://blog.codefx.org/tools/maven-on-java-9/#Switching-Maven8217s-JVM-Between-Java-8-And-9 and try to get behind how to use profiles that can be activated based on the `<jdk>` property...

**Pull request closed without merging**
