### PR TITLE
Add revapi-maven-plugin configuration

### PR DESCRIPTION
**Pull request by imagejan**
Closes https://github.com/scijava/scijava-scripts/issues/27.

### CODE REVIEW

**Comment by ctrueden** [comment]
Great!

**Comment by frauzufall** [comment]
Adding this means any project using `pom-scijava` will get an error when during `mvn install` for anything breaking the API, right? Isn't that too radical?

**Comment by imagejan** [comment]
No, it just gives you the possibility to run `mvn revapi:check` to check for errors. It doesn't change the default goal `install` (if I understood correctly how maven works).

**Comment by frauzufall** [comment]
If I add this to a project and run `mvn install`, it does get executed. I also don't completely understand why but plugins can define default phases a goals is bound to and my guess is since we add this `check` goal to `execution` is is by default executed during install. Probably defined somewhere in the revapi parent POM ([link](https://github.com/revapi/revapi/blob/master/revapi-build/pom.xml))?

**Comment by frauzufall** [comment]
Removing the `executions` part makes it not do this during `install`. I filed a [PR](https://github.com/scijava/pom-scijava-base/pull/18). Let me know if I'm completely missing the point :smile:

**Comment by ctrueden** [comment]
I noticed the execution block, but I thought @imagejan wanted that behavior, sorry. Because it was added to `<pluginManagement>`, I figured people who wanted the build to fail would enable it by adding it to the `<plugins>` (outside `<pluginManagement>`) of their POM downstream.

Anyway, it's fine also not to have the default execution, and instead people who want it to run automatically to add their own execution. So I merged your PR, @frauzufall. I am releasing pom-scijava-base 11.1.1 with that fix now. Note that this is the last pom-scijava-base we can ever release, since 11.1.1 is the perfect version number! 😜

**Comment by imagejan** [comment]
Sorry for the confusion. So now, without the `<execution>` block, we can actually also add `revapi` in the `<plugins>` of `pom-scijava`, to give every project the *possibility* of running `mvn revapi:check`, right?

**Comment by frauzufall** [comment]
Haha, then  was wrong too, I thought it would be forced for everyone this way, but didn't notice the `pluginManagement` location. I guess it's both fine :sweat_smile:

It'd be great to add it to the release script. Or have something like a pre-release script, checking for API differences, generating changelogs... I anyways wanted to give the changelogs topic a push in the near future..

**Pull request merged**
